export const BENCH_DISPATCH_AMBIGUOUS_CODE =
  "FORGE_DISPATCH_AMBIGUOUS" as const;

export const BENCH_DISPATCH_RECONCILED_CODE =
  "FORGE_DISPATCH_RECONCILED" as const;

export const BENCH_DISPATCH_RECONCILIATION_FAILED_CODE =
  "FORGE_DISPATCH_RECONCILIATION_FAILED" as const;
